In [38]:
language = ["Java","Python","R"]
version=[14,3,10]

In [6]:
result=zip(language,version)

In [7]:
print(list(result))

[('Java', 14), ('Python', 3), ('R', 10)]


# Pandas

In [2]:
data = {'Name':['Tom','nick','krish','Jack'],'Age':[20,16,40,18]}


In [3]:
import pandas as pd

In [4]:
df_emp=pd.DataFrame(data)
print(df_emp)

Name  Age
0    Tom   20
1   nick   16
2  krish   40
3   Jack   18

In [6]:
serEmplAge= pd.Series(df_emp['Age'])
serEmplAge

0    20
1    16
2    40
3    18
Name: Age, dtype: int64

In [8]:
type(serEmplAge)

pandas.core.series.Series

In [9]:
result = serEmplAge.apply(lambda x: 21 if x==18 else x)

In [12]:
result

0    20
1    16
2    40
3    21
Name: Age, dtype: int64

In [35]:
lst=[x**2 for x in range(1,10)] # List comprehension

In [36]:
lst

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [41]:
l1=[x for x in language]
l1   

['Java', 'Python', 'R']

# Numpy Arrays

Array creation Functions
np.array(),np.zeros(),np.ones(),np.empty()

In [44]:
import numpy as np
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [46]:
array2= np.zeros((3,3))
array2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
array3=np.ones((2,4))
array3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [51]:
array4=np.random.rand(100)
array4

array([0.33268216, 0.81111568, 0.16960827, 0.05103846, 0.85992953,
       0.5404199 , 0.0620132 , 0.8827471 , 0.27344392, 0.48442202,
       0.1864013 , 0.04850829, 0.10456495, 0.75971395, 0.78702194,
       0.79988641, 0.98748584, 0.83843677, 0.19029563, 0.20757231,
       0.78695816, 0.00460116, 0.86519289, 0.90752423, 0.24004419,
       0.36149682, 0.63618368, 0.68341474, 0.6744345 , 0.14447992,
       0.84595768, 0.5195565 , 0.36251685, 0.25312364, 0.84676497,
       0.25318288, 0.62911044, 0.00778042, 0.27246375, 0.8609267 ,
       0.08793723, 0.76430637, 0.79831563, 0.3748243 , 0.02213546,
       0.68934267, 0.67665389, 0.95341776, 0.53407655, 0.1839673 ,
       0.87318447, 0.76832014, 0.32384481, 0.46221077, 0.32646198,
       0.3725939 , 0.61359747, 0.79954612, 0.67991053, 0.92776816,
       0.09542217, 0.32552766, 0.48334056, 0.27083561, 0.6690762 ,
       0.65355499, 0.18253539, 0.14509202, 0.41445136, 0.91320927,
       0.72542705, 0.81038937, 0.74897893, 0.91686421, 0.62678

In [53]:
array1d=np.array([1,2,3,4,5,6,7,8,9])
array2d=np.reshape(array1d,(3,3))
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr=np.random.rand(30)
arr2=np.reshape(arr,(6,5))
arr2

array([[0.90814114, 0.10101117, 0.08489817, 0.77210889, 0.24065284],
       [0.23930582, 0.01543474, 0.47228879, 0.28218803, 0.69517333],
       [0.41375471, 0.30505126, 0.00376919, 0.54724292, 0.59839726],
       [0.1945697 , 0.4407454 , 0.46548281, 0.97010352, 0.91067225],
       [0.61594757, 0.07330944, 0.69452073, 0.62373926, 0.51171234],
       [0.22632375, 0.73618093, 0.83616546, 0.49542987, 0.12602413]])

# Array Input and Output Function

In [56]:
#np.save(),np.loadtxt()

In [57]:
array1=np.array([[1,2,3],[4,5,6]])

In [58]:
np.savetxt('data.txt',array1)

In [59]:
loaded_data=np.loadtxt('data.txt')

In [60]:
print(loaded_data)

[[1. 2. 3.]
 [4. 5. 6.]]


In [61]:
type(loaded_data)

numpy.ndarray